### ISSUE TITLE
Payload doesn't run on PICO W, instead folder opens.

### ISSUE THREAD

**Issue by ilan1009** [dbisu/pico-ducky#170]
**Describe the issue**
I have setup correctly, have payload.dd, code.py is correct, have the correct libs, but when i connect to my windows 11 computer, the folder for the circuitpy drive opens but no payload runs

I know many have posted this issue but i couldn't find a solution by reading that.

![2023-04-16 17_42_03-CIRCUITPY (E_)](https://user-images.githubusercontent.com/51132557/232320686-6b9fcb19-76fa-4f86-adcd-fd0c56b68da8.png)
^^ file structure

I even logged in with putty, not sure what I'm supposed to see here.

![Uploading 2023-04-16 17_42_53-New Issue · dbisu_pico-ducky — Mozilla Firefox.png…]()

will take any help LOL, hope my board isnt messed up

**Comment by ilan1009** [comment]
```

>>> exec(open("code.py").read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 111, in <module>
ValueError: GP22 in use

```

some insight maybe

**Comment by ilan1009** [comment]
its a dick move to not explain how you fixed the  issue, but i fixed it, and not sure im fit to explain.
