### ISSUE TITLE
Duckyscript 3 Commands not Working

### ISSUE THREAD

**Issue by ToxicMonster** [dbisu/pico-ducky#297]
**Describe the issue**
Duckyscript 3 commands are not working when added to `payload.dd` file including `WAIT_FOR_BUTTON_PRESS`, functions and variables

**To Reproduce**
Add one of the duckyscript 3 commands to payload

**Expected behavior**
Duckyscript 3 command executes as per [Hak5 docs](https://docs.hak5.org/hak5-usb-rubber-ducky/duckyscript-tm-quick-reference).

**Additional context**
Addition of duckyscript 3 commands would greatly increase functionality of pico as rubber ducky.

**Comment by dbisu** [comment]
I'll have some time in a couple of weeks to take a look at this issue.

**Comment by stilllearning65** [comment]
tried using the functions.dd as just a regular payload.dd file.
nothing happens.


Auto-reload is off.
code.py output:
starting monitor_buttons
progStatus False
Finding payload
starting monitor_led_changes
starting blink_pico_led
Running
runScript: REM Example Function

runScript: FUNCTION COUNTDOWN()

runScript: COUNTDOWN()

runScript:
-- MANUALLY TERMINATED AFTER 1 MIN. --
Traceback (most recent call last):
  File "code.py", line 91, in <module>
  File "asyncio/core.py", line 346, in run
  File "asyncio/core.py", line 283, in run_until_complete
  File "duckyinpython.py", line 599, in monitor_buttons
  File "adafruit_debouncer.py", line 100, in update
KeyboardInterrupt:

Code done running.

**Comment by dbisu** [comment]
OK, I'll have to take a look. I've got several personal projects I need to work on, so might be a little bit until I can figure out what is going on.

**Comment by stilllearning65** [comment]
OKAY!
No rush
________________________________

**Comment by stilllearning65** [comment]
I did some testing and a believe ducky 4.0 is the problem with while loops and functions.
Attached is a txt file from CP v9.2.9; DUCKY3/13/25 & CPv10.0.3; DUCKY v3.2 an last CP v10.0.3: DUCKY v4.0. First 2 work fine.
Payload in txt file at end
________________________________

**Comment by dbisu** [comment]
OK, thanks for the info. Sounds like I have a bad merge in there.

**Comment by stilllearning65** [comment]
I compared the function an while lines an they are the same
________________________________
